### PR TITLE
CASMINST-4940 CSM 1.3 Upgrade changes -- update potential cloud-init …

### PR DESCRIPTION
**Pull request by atifsyedali**
### Summary and Scope

- Fixes: CASMINST-4940

This introduces a new upgrade method for 1.2 to 1.3 upgrades. This is a stop gap mechanism and we aim to overhaul this flow entirely for 1.4.

Please note that:
1. The changes are a duplicate of the 1.0 to 1.2 upgrade method, without any of the networking stuff (IPAM and ifname updates). 
2. I consciously chose to duplicate the image updates code rather than refactor it into a separate method to avoid regressions as we add more items into the 1.2 to 1.3 upgrade.
3. There would be an accompanying change in docs-csm/prerequisites.sh that would reference this new command line parameter.
4. I am unsure of how to test this and would need some guidance.

#### Issue Type

- Install task

### Prerequisites

- [ ] I have included documentation in my PR (or it is not required)
- [ ] I tested this on internal system (if yes, please include results or a description of the test)
- [ ] I tested this on a vshasta system (if yes, please include results or a description of the test)
 
### Idempotency
 
Same as existing code.
 
### Risks and Mitigations
 
Changes are fairly isolated end-to-end so low risk.

### CODE REVIEW

**Comment by heemstra** [comment]
@dzou-hpe did some testing for the original option - but I believe that was typically done during a full upgrade scenario.  I'd still check with him.

Looks like some unit tests that call `updateBSS()` need to be updated.  Looking into why that didn't fail the build.

Happy to hear this flow will be overhauled in the future. 😄

**Comment by heemstra** [comment]
> Looks like some unit tests that call updateBSS() need to be updated. Looking into why that didn't fail the build.

This will be fixed here: https://github.com/Cray-HPE/cray-site-init/pull/205

**Comment by rustydb** [comment]
Rebased to pull in fixed unit tests for the failures in `main`.

**Comment by rustydb** [comment]
The current failing unit tests look like they correctly pertain to this PR.

**Comment by atifsyedali** [comment]
Sorry guys, I have been meaning to update this PR for a week now but got pulled into too many meetings this week. Updated to at least fix the unit tests, but didn't add new new unit tests.

**Review by rustydb — APPROVED** [review]

**Comment by rustydb** [comment]
This requires a doc change: https://github.com/Cray-HPE/docs-csm/pull/2054

**Pull request merged**
